### ISSUE TITLE
maven下载的时候会下载不下来，红线提示

### ISSUE THREAD

**Issue by rhettpang** [SpringForAll/spring-boot-starter-swagger#107]
主要是依赖的springfox-swagger-ui版本里面设置的是2.9.0.
但是maven仓库中找不到这个版本，最新版为2.9.2.所以手动将版本改为2.9.2或者2.9.1
`    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <version.java>1.8</version.java>
        <version.swagger>2.9.2</version.swagger>
        <version.spring-boot>1.5.10.RELEASE</version.spring-boot>
        <version.lombok>1.16.18</version.lombok>
    </properties>`

**Comment by dyc87112** [comment]
1.8.0已升级swagger版本至2.9.2
