### ISSUE TITLE
Response headers date 差8小时

### ISSUE THREAD

**Issue by shmilymin** [SpringForAll/spring-boot-starter-swagger#123]
Response headers
 content-type: application/json;charset=UTF-8 
 date: Sat, 24 Nov 2018 03:08:34 GMT 
 transfer-encoding: chunked

**Comment by huotaihe** [comment]
是调用的本地？还是服务器端？

**Comment by huotaihe** [comment]
正在定位你的问题，会尽快在回复你。

**Comment by shmilymin** [comment]
本地

**Comment by huotaihe** [comment]
你好，我查了一下这并不是框架的bug。
http的规范所有头信息时间都必须以格林威治时间表示

> All HTTP date/time stamps MUST be represented in Greenwich Mean Time (GMT), without exception.

可以参考：https://stackoverflow.com/questions/21120882/the-date-time-format-used-in-http-headers

你可以去看一下谷歌、百度、天猫等大网站都是用gmt时区的时间来表示的，刚好比北京时间(GMT+8) 晚8个小时。

希望可以帮到你。
暂时没有找到修改的方法，而且也不建议修改。

**Comment by xiaojun29** [comment]
> 你好，我查了一下这并不是框架的bug。
> http的规范所有头信息时间都必须以格林威治时间表示
> 
> > All HTTP date/time stamps MUST be represented in Greenwich Mean Time (GMT), without exception.
> 
> 可以参考：https://stackoverflow.com/questions/21120882/the-date-time-format-used-in-http-headers
> 
> 你可以去看一下谷歌、百度、天猫等大网站都是用gmt时区的时间来表示的，刚好比北京时间(GMT+8) 晚8个小时。
> 
> 希望可以帮到你。
> 暂时没有找到修改的方法，而且也不建议修改。

确实，自己虽然知道了，但是给其他人看的时候，总是觉得很怪！
