### ISSUE TITLE
Please indicate a valid Swagger or OpenAPI version field

### ISSUE THREAD

**Issue by Tomones** [SpringForAll/spring-boot-starter-swagger#138]
集成swagger 报错The provided definition does not specify a valid version field.

Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match  openapi: 3.0.n (for example, openapi: 3.0.0).

**Comment by lgf-Allen** [comment]
你好，能提供下具体的使用场景和报错日志么？

**Comment by vectooor** [comment]
遇到类似问题。有解决吗？

**Comment by DimonHo** [comment]
![image](https://user-images.githubusercontent.com/3371641/57342392-60c0c500-7171-11e9-9e32-75b3c9ef1489.png)
![image](https://user-images.githubusercontent.com/3371641/57342397-6a4a2d00-7171-11e9-822a-1232a2dc0c66.png)
同问  配置错在哪?

**Comment by DimonHo** [comment]
我的问题找到了，是因为我用了gson序列化，swagger解析配置的时候会有问题。
swagger与gson不兼容。

**Comment by DimonHo** [comment]
解决方案：  https://blog.csdn.net/liyiming2017/article/details/83550359

**Comment by Tomones** [comment]
> 遇到类似问题。有解决吗？
没解决 后来升级到1.9版本就好了

**Comment by j796160836** [comment]
Use WebMvcConfiguration and re-write resourceHandlers then solve the problem.

```
@Configuration
@EnableWebMvc
@EnableSwagger2
class WebConfig : WebMvcConfigurationSupport() {
    override fun addResourceHandlers(registry: ResourceHandlerRegistry) {
        registry.addResourceHandler("swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");

        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");

        super.addResourceHandlers(registry)
    }
}
```


Reference:
https://stackoverflow.com/questions/36744678/spring-boot-swagger-2-ui-custom-requestmappinghandlermapping-mapping-issue
