### ISSUE TITLE
maven下载不来最新的版本，红线提示

### ISSUE THREAD

**Issue by bluesmi** [SpringForAll/spring-boot-starter-swagger#144]
![image](https://user-images.githubusercontent.com/18614103/56501327-ec670e80-6540-11e9-9f35-6d140b654e4d.png)
![image](https://user-images.githubusercontent.com/18614103/56501331-f557e000-6540-11e9-9eda-cd61c6d72eb4.png)

**Comment by dyc87112** [comment]
https://search.maven.org/artifact/com.spring4all/swagger-spring-boot-starter/1.9.0.RELEASE/jar

检查下网络啥的原因？
