### ISSUE TITLE
使用@EnableSwagger2Doc注解启动程序报错，使用@EnableSwagger2注解启动正常

### ISSUE THREAD

**Issue by zengdingxin** [SpringForAll/spring-boot-starter-swagger#150]
[ehs-consumer-manager.zip](https://github.com/SpringForAll/spring-boot-starter-swagger/files/3169058/ehs-consumer-manager.zip)
 附件为代码程序

**Comment by developlee** [comment]
看了你的代码，在application.yml中，你有这样一段代码书写是错误的：
```java
globalOperationParameters:
  - name: token
  - description: token身份认证
  - modelRef: header
  - parameterType: true
```

globalOperationParameters是一个对象 ，而不是一个数组，正确的写法应该：

```java
  globalOperationParameters:
    name: token
    description: "token身份认证"
    modelRef: header
    parameterType: true
```

**Comment by developlee** [comment]
> [ehs-consumer-manager.zip](https://github.com/SpringForAll/spring-boot-starter-swagger/files/3169058/ehs-consumer-manager.zip)
> 附件为代码程序

#### 看了你的代码，在application.yml中，你有这样一段代码书写是错误的，这样导致无法正确刷新应用上下文。
```java
globalOperationParameters:
  - name: token
  - description: token身份认证
  - modelRef: header
  - parameterType: true
```

globalOperationParameters是一个对象 ，而不是一个数组，正确的写法应该：

```java
  globalOperationParameters:
    name: token
    description: "token身份认证"
    modelRef: header
    parameterType: true
```

**Comment by zengdingxin** [comment]
这个配置调整过来已经OK了，现在API有重复生成，加了api的注解有重复生成没加不会，代码还是之前的附件
![微信截图_20190512193942](https://user-images.githubusercontent.com/14012002/57581710-dae4a700-74ed-11e9-8d3d-7057b1937b16.png)
![微信截图_20190512193958](https://user-images.githubusercontent.com/14012002/57581711-db7d3d80-74ed-11e9-99e3-c5f45603192f.png)

**Comment by zengdingxin** [comment]
UserController1 文件

**Comment by zengdingxin** [comment]
[UserController1.txt](https://github.com/SpringForAll/spring-boot-starter-swagger/files/3170018/UserController1.txt)

**Comment by developlee** [comment]
> 这个配置调整过来已经OK了，现在API有重复生成，加了api的注解有重复生成没加不会，代码还是之前的附件
> ![微信截图_20190512193942](https://user-images.githubusercontent.com/14012002/57581710-dae4a700-74ed-11e9-8d3d-7057b1937b16.png)
> ![微信截图_20190512193958](https://user-images.githubusercontent.com/14012002/57581711-db7d3d80-74ed-11e9-99e3-c5f45603192f.png)
RequestMapping 注解未指定请求方式

**Comment by zengdingxin** [comment]
自己的问题

**Comment by DimonHo** [comment]
> > [ehs-consumer-manager.zip](https://github.com/SpringForAll/spring-boot-starter-swagger/files/3169058/ehs-consumer-manager.zip)
> > 附件为代码程序
> 
> #### 看了你的代码，在application.yml中，你有这样一段代码书写是错误的，这样导致无法正确刷新应用上下文。
> ```java
> globalOperationParameters:
>   - name: token
>   - description: token身份认证
>   - modelRef: header
>   - parameterType: true
> ```
> 
> globalOperationParameters是一个对象 ，而不是一个数组，正确的写法应该：
> 
> ```java
>   globalOperationParameters:
>     name: token
>     description: "token身份认证"
>     modelRef: header
>     parameterType: true
> ```

globalOperationParameters是数组，你的回答要误导别人了
![image](https://user-images.githubusercontent.com/3371641/81401153-50b33b00-9161-11ea-876d-648da0ba8f5f.png)

**Comment by DimonHo** [comment]
> > > [ehs-consumer-manager.zip](https://github.com/SpringForAll/spring-boot-starter-swagger/files/3169058/ehs-consumer-manager.zip)
> > > 附件为代码程序
> > 
> > 
> > #### 看了你的代码，在application.yml中，你有这样一段代码书写是错误的，这样导致无法正确刷新应用上下文。
> > ```java
> > globalOperationParameters:
> >   - name: token
> >   - description: token身份认证
> >   - modelRef: header
> >   - parameterType: true
> > ```
> > 
> > 
> > globalOperationParameters是一个对象 ，而不是一个数组，正确的写法应该：
> > ```java
> >   globalOperationParameters:
> >     name: token
> >     description: "token身份认证"
> >     modelRef: header
> >     parameterType: true
> > ```
> 
> globalOperationParameters是数组，你的回答要误导别人了
> ![image](https://user-images.githubusercontent.com/3371641/81401153-50b33b00-9161-11ea-876d-648da0ba8f5f.png)


这个配置正确的写法应该是这样：
```
swagger:
  global-operation-parameters:
    - name: "Authorization"
      description: "user Authorization"
      modelRef: "string"
      parameterType: "header"
      required: "false"
```
