### ISSUE TITLE
1.8.0.RELEASE以上 无法使用 @EnableSwagger2Doc注解，无法配置参数

### ISSUE THREAD

**Issue by huangliangyun** [SpringForAll/spring-boot-starter-swagger#153]
1.8.0.RELEASE以上 无法使用 @EnableSwagger2Doc注解，只能使用@EnableSwagger2，也无法进行参数配置，但能查看多个服务的API

**Comment by NewProgrammerJin** [comment]
同问

**Comment by liululee** [comment]
> 1.8.0.RELEASE以上 无法使用 @EnableSwagger2Doc注解，只能使用@EnableSwagger2，也无法进行参数配置，但能查看多个服务的API



> 同问

感谢提issue，之前已经有一个同样的问题，你们可参考下：https://github.com/SpringForAll/spring-boot-starter-swagger/issues/150
