### ISSUE TITLE
1.9.0.RELEASE 访问接口文档报NumberFormatException错原因及解决办法

### ISSUE THREAD

**Issue by lyuzb** [SpringForAll/spring-boot-starter-swagger#175]
使用swagger-ui.html访问时后台报错:java.lang.NumberFormatException: For input string: "".

原因是io.springfox:springfox-swagger-ui:2.92版本的jar包内置为io.swagger:swagger-models包为1.5.20版本.

1.5.20版本中判断example只判断是否为null,没有判断example为空字符串""的情况所以报错.1.5.21版本新增了判断example是否为null和"".所以排除1.5.20包重新导入1.5.21包即可解决.

<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>2.9.2</version>
    <exclusions>
        <exclusion>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-models</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-models</artifactId>
    <version>1.5.21</version>
</dependency>

**Comment by dyc87112** [comment]
1.9.1.RELEASE已升级该包，感谢反馈
