### ISSUE TITLE
swagger.exclude-path 不起作用

### ISSUE THREAD

**Issue by jinianjun** [SpringForAll/spring-boot-starter-swagger#181]
版本1.7.0.
排除路径时，已将/actuator/**,/errpr/**,/ops/**都排除在外，但在swagger-ui中，还是可以能看到相关接口。

![WechatIMG409](https://user-images.githubusercontent.com/3350476/72230932-7b4a1880-35f3-11ea-9e2e-856fc1144719.jpeg)

**Comment by dyc87112** [comment]
/error拼错，/actuator/改为/actuator/**
