### ISSUE TITLE
springcloud在加载swagger的问题

### ISSUE THREAD

**Issue by zhangtao546** [SpringForAll/spring-boot-starter-swagger#186]
在开启了swagger之后,在向eureka注册服务成功       之后会加载swagger配置,加载完配置之后服务才会完全启动.
在注册成功和加载swagger期间会有服务请求进来,会报503异常.   是否可以调整swagger的加载顺序,在服务注册之前去加载?

**Comment by dyc87112** [comment]
我们一直用但是没碰到过这个情况嘛，可以看看你应用里的注册调用是在哪里，如果缺失太靠前，可以考虑改造一下，放到应用起到的最后。或者也可以根据你说的改造swagger的初始化过程。具体如何切入，看看spring 的事件机制：http://blog.didispace.com/Spring-Boot-2-0-feature-2-ApplicationStartedEvent/
