### ISSUE TITLE
hibernate校验器注解支持

### ISSUE THREAD

**Issue by Pomelo1001** [SpringForAll/spring-boot-starter-swagger#188]
目前提供了对JSR-303校验注解支持（1.5.0 + 支持）
 @NotNull
@Max、@Min
@Size
@Pattern
对hibernate的支持能否也集成一下

**Comment by dyc87112** [comment]
这个是swagger去做的，这个项目主要是swagger基础上的配置转移到配置文件中，不涉及对swagger自身的扩展
