### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by 112921482** [SpringForAll/spring-boot-starter-swagger#189]
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: javax/validation/constraints/Min

自行引入javax.validation:validation-api:2.0.1.Final后不报错，请问是否属于BUG

**Comment by dyc87112** [comment]
不是bug哦，对于验证这块的具体实现是需要用户自己引入的，因为又很多种。如果我们强制写进去了，可能会跟你自己的冲突
