### ISSUE TITLE
请问该项目是否不再维护了？我项目启动，显示循环依赖

### ISSUE THREAD

**Issue by Githubbili** [SpringForAll/spring-boot-starter-swagger#197]
`***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.spring4all.swagger.SwaggerAutoConfiguration.createRestApi(SwaggerAutoConfiguration.java:98)

The following method did not exist:

    springfox.documentation.builders.PathSelectors.ant(Ljava/lang/String;)Lcom/google/common/base/Predicate;

The method's class, springfox.documentation.builders.PathSelectors, is available from the following locations:

    jar:file:/E:/Code/maven-repository/io/springfox/springfox-core/3.0.0/springfox-core-3.0.0.jar!/springfox/documentation/builders/PathSelectors.class

The class hierarchy was loaded from the following locations:

    springfox.documentation.builders.PathSelectors: file:/E:/Code/maven-repository/io/springfox/springfox-core/3.0.0/springfox-core-3.0.0.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of springfox.documentation.builders.PathSelectors

Disconnected from the target VM, address: '127.0.0.1:1892', transport: 'socket'

Process finished with exit code 0
`

我的springboot-parent版本是
`<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.3.5.RELEASE</version>`

**Comment by xuxin103** [comment]
解决了吗?

**Comment by dyc87112** [comment]
spring boot 2.3.5应该没问题的，但是看你报错springfox用了3.0，应该自己用了我们的内容，又自己指定了其他版本吧。使用问题。建议按文档时候，springfox 3.0目前还没支持。
