### ISSUE TITLE
分组名称不能使用中文

### ISSUE THREAD

**Issue by ascendlin** [SpringForAll/spring-boot-starter-swagger#212]
> swagger.docket.后台.title=后台接口

启动不了
No converter found capable of converting from type [java.lang.String] to type [com.spring4all.swagger.SwaggerProperties$DocketInfo]

**Comment by dyc87112** [comment]
换YAML格式配置试试

**Comment by ascendlin** [comment]
> 换YAML格式配置试试

一样的不支持

**Comment by dyc87112** [comment]
哦，是给参数里带中文，这个不行。我们没有这个参数。

不是程序问题，是使用问题
