### ISSUE TITLE
application.properties配置swagger.title等中文乱码

### ISSUE THREAD

**Issue by alieismy** [SpringForAll/spring-boot-starter-swagger#24]
文件格式UTF8，配置swagger.title为中文，在chrome打开是乱码。

**Comment by tyyr1998** [comment]
前一段时间也是因为这个问题，没有用成这个包。
最简单的解决办法是把配置文件改成yaml格式的就可以了，原因是spring boot 会默认使用unicode读application.properties。（或者你可以把配置文件的汉字都改成unicode？ :) ）

**Comment by dyc87112** [comment]
@tyyr1998 感谢帮忙答疑~

**Comment by JKAK47** [comment]
直接用属性文件就不能解决了吗？

**Comment by pikefeier** [comment]
如果不改properties文件，可以在setting-fileencoding中勾选 transparent native to ascii conversation
![image](https://user-images.githubusercontent.com/26399587/185063142-992253ac-5d5c-4001-86ff-3bf296182568.png)
