### ISSUE TITLE
Maven 仓库只有1.0.0版本

### ISSUE THREAD

**Issue by leongfeng** [SpringForAll/spring-boot-starter-swagger#28]
其它版本的下载不了呀

**Comment by dyc87112** [comment]
做过迁移，填一下你的xml配置？

**Comment by dyc87112** [comment]
确定了一下，都是有的：
![image](https://user-images.githubusercontent.com/3391170/31974284-76be76e0-b95d-11e7-8b0d-b082dc56ac1b.png)
