### ISSUE TITLE
希望能增加ignoredParameterTypes的配置功能！

### ISSUE THREAD

**Issue by winixi** [SpringForAll/spring-boot-starter-swagger#34]
如何配置几个全局要忽略的控制器参数？每次都要@ApiIgnore太麻烦。
我看代码方式配置是可以做到的，但是用你的配置如何写（我看源码好像没有实现）？或如何用配置类修改全局参数？

代码示例
Docket docket = new Docket();
docket.ignoredParameterTypes(SessionTo.class, NewResponse.class);

**Comment by dyc87112** [comment]
1.6.0 support
