### ISSUE TITLE
希望增加自定义的返回消息状态码配置

### ISSUE THREAD

**Issue by winixi** [SpringForAll/spring-boot-starter-swagger#35]
下面是代码，希望增加配置写法！
.useDefaultResponseMessages(false)                                   
.globalResponseMessage(RequestMethod.GET,                     
  newArrayList(new ResponseMessageBuilder()   
    .code(500)
    .message("500 message")
    .responseModel(new ModelRef("Error"))
    .build(),
    new ResponseMessageBuilder() 
      .code(403)
      .message("Forbidden!")
      .build()));

**Comment by JeffLi1993** [comment]
好的 在处理

**Comment by JeffLi1993** [comment]
`
swagger.apply-default-response-messages=false
swagger.global-response-message.message500=401401message
swagger.global-response-message.model-ref500=ERROR
`
这样配置可好

**Comment by JeffLi1993** [comment]
`swagger.apply-default-response-messages=false`
`swagger.global-response-messages[0].code=401`
`swagger.global-response-messages[0].message=Forbidden！！`
`swagger.global-response-messages[1].code=500`
`swagger.global-response-messages[1].message=500 message`
`swagger.global-response-messages[1].modelRef=ERROR`

还是这样呢？

**Comment by renlulu** [comment]
喜欢下面的那个

**Comment by JeffLi1993** [comment]
swagger.apply-default-response-messages=false
swagger.global-response-messages.GET[0].code=401
swagger.global-response-messages.GET[0].message=Forbidden！！
swagger.global-response-messages.GET[1].code=500
swagger.global-response-messages.GET[1].message=500 message
swagger.global-response-messages.GET[1].modelRef=ERROR
swagger.global-response-messages.POST[0].code=401
swagger.global-response-messages.POST[0].message=Forbidden！！

**Comment by dyc87112** [comment]
还有一些bug要修  @JeffLi1993

**Comment by JeffLi1993** [comment]
// 取消使用默认预定义的响应消息,并使用自定义响应消息
swagger.apply-default-response-messages=false
swagger.global-response-message.get[0].code=401
swagger.global-response-message.get[0].message=401get
swagger.global-response-message.get[1].code=500
swagger.global-response-message.get[1].message=500get
swagger.global-response-message.get[1].modelRef=ERROR
swagger.global-response-message.post[0].code=500
swagger.global-response-message.post[0].message=500post
swagger.global-response-message.post[0].modelRef=ERROR

**Comment by dyc87112** [comment]
1.6.0 support
