### ISSUE TITLE
分组后, api-docs 这个url就取不到值了, 得加 group 参数, 希望一个文档包含多个group就不行了

### ISSUE THREAD

**Issue by jamesyc33** [SpringForAll/spring-boot-starter-swagger#50]
您好, 根据您的 DemoApplicationTest 文件中描述 , url 填写 http://localhost:8080/v2/api-docs 时, 在未分组的情况下, 是可以生成文档的, 只不过几十个接口很乱, 因此我希望进行分组

但是, 在 application.properties 加入分组后, 该 url 我试了没有任何返回值, 需要修改成 http://localhost:8080/v2/api-docs?group=user 才可以, 也就是需要写死 group 参数

那么, 我希望一个文档包含所有 group , 应该如何做呢?

另外, 生成的文档是 adoc 和 md 格式的 ,  我希望弄成 左侧是目录, 右侧是正文的 这种格式, 该如何做呢? 我看官方是可以的

**Comment by dyc87112** [comment]
先回复第二个问题，可以参考下我这篇博文的设置：http://blog.didispace.com/swagger2markup-asciidoc/
