### ISSUE TITLE
能否把swagger.enabled的缺省配置改为false？

### ISSUE THREAD

**Issue by allen-kaiser-cai** [SpringForAll/spring-boot-starter-swagger#70]
在生产环境中，因为安全原因这个开关应该要关闭。但还需要加上一个配置swagger.enabled=false才行。建议swagger.enabled缺省值改为false。在开发和测试环境中需要支持的才打开。

**Comment by dyc87112** [comment]
如果用spring cloud config的话，在不同环境配置中做不同设置即可。后续会考虑增加一个参数来设置默认打开或关闭的profiles，这样设一个地方就好了，根据不同环境直接开关。
