### ISSUE TITLE
可否直接整合多个spring cloud项目,每个项目都有单独的swagger配置,即每个分组都是单独的项目

### ISSUE THREAD

**Issue by guangnix** [SpringForAll/spring-boot-starter-swagger#71]

**Comment by kangminze** [comment]
同样碰到这个问题，单个的方便了，希望多个也能解决下

**Comment by gumutianqi** [comment]
这个问题推荐借助第三方工具

**Comment by guangnix** [comment]
有什么好推荐的吗   这个搞了好久一直整合不出来




------------------ 原始邮件 ------------------
发件人: "古木天琪"<notifications@github.com>;
发送时间: 2018年3月29日(星期四) 中午11:19
收件人: "SpringForAll/spring-boot-starter-swagger"<spring-boot-starter-swagger@noreply.github.com>;
抄送: "寻路"<164301097@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [SpringForAll/spring-boot-starter-swagger] 可否直接整合多个spring cloud项目,每个项目都有单独的swagger配置,即每个分组都是单独的项目 (#71)




这个问题推荐借助第三方工具

**Comment by Rebellioncry** [comment]
同样问题，多个微服务的接口如何整合到一个页面的不同分组？好像原生的可以做https://blog.csdn.net/qq6492178/article/details/78863935，这个boot的不支持吗？

**Comment by dyc87112** [comment]
写了个例子，大家可以参考一下：http://blog.didispace.com/Spring-Cloud-Zuul-use-Swagger-API-doc/
