### ISSUE TITLE
配置文件中文乱码

### ISSUE THREAD

**Issue by imhuzi** [SpringForAll/spring-boot-starter-swagger#74]
配置文件中文乱码

**Comment by jisixiao** [comment]
这个问题我也遇到了，有人说是在修改配置文件的编码格式，但是貌似不太实用

**Comment by samluby** [comment]
当配置文件中配置有中文的value时，比如swagger.title=测试
像这样的就会出现中文乱码，请问下你们解决了吗》？？如果解决了麻烦帮我解答下，多谢了。

**Comment by C644753271** [comment]
配置文件中配置有中文的value时，页面显示乱码

**Comment by just-moth** [comment]
## idea项目中这样设置的
![image](https://user-images.githubusercontent.com/36361486/40220369-7c986e28-5aab-11e8-85d8-f8849b0ebd12.png)
## properties文件在idea项目中
![image](https://user-images.githubusercontent.com/36361486/40220425-a7b1ec10-5aab-11e8-951a-6d7d79fc3aac.png)
## properties文件拿出来单独打开
![image](https://user-images.githubusercontent.com/36361486/40220459-c395b862-5aab-11e8-9ae6-b36fa0e3a97a.png)

## 暂时这样解决的
