### ISSUE TITLE
多个不同的微服务的api怎么做分组？

### ISSUE THREAD

**Issue by Rebellioncry** [SpringForAll/spring-boot-starter-swagger#75]
https://blog.csdn.net/qq6492178/article/details/78863935
原生的可以做，但是用这个boot版的要怎么做？我看那个分组功能好像只是一个项目里分组

**Comment by dyc87112** [comment]
新鲜出炉，供参考：http://blog.didispace.com/Spring-Cloud-Zuul-use-Swagger-API-doc/
