### ISSUE TITLE
标题中文显示乱码

### ISSUE THREAD

**Issue by longstorying** [SpringForAll/spring-boot-starter-swagger#85]
中文乱码怎么解决。

**Comment by dyc87112** [comment]
properties文件中中文需要配置成unicode

**Comment by longstorying** [comment]
谢谢
发送自 Windows 10 版邮件应用

发件人: 程序猿DD-翟永超
发送时间: 2018年5月23日 17:16
收件人: SpringForAll/spring-boot-starter-swagger
抄送: longstorying; Author
主题: Re: [SpringForAll/spring-boot-starter-swagger] 标题中文显示乱码 (#85)

properties文件中中文需要配置成unicode

**Comment by longstorying** [comment]
老哥再问你一个问题。希望能给我解答。谢谢。
@ApiOperation(value = "测试")
@PostMapping("index")
@ApiImplicitParam(name = "map", value = "map集合")
public String index(@RequestBody Map<String, Object> map) {
    return "111";
}
像这种@RequestBody map接收swagger怎么描述这个map。
发送自 Windows 10 版邮件应用

发件人: 程序猿DD-翟永超
发送时间: 2018年5月23日 17:16
收件人: SpringForAll/spring-boot-starter-swagger
抄送: longstorying; Author
主题: Re: [SpringForAll/spring-boot-starter-swagger] 标题中文显示乱码 (#85)

properties文件中中文需要配置成unicode
