### ISSUE TITLE
jenkins打包部署问题

### ISSUE THREAD

**Issue by KochamCie** [SpringForAll/spring-boot-starter-swagger#86]
背景：项目是springboot，使用Jenkins构建打包成可执行jar的项目。
本地开发没有问题，无论是idea打包或者是project下mvn install。

多模块下，在common模块中引入了starter-swagger依赖，开发过程中是没问题的，
但是到Jenkins进行构建时，model模块(使用到了swagger一系列api或model的注解)，和其他模块
如下报错：BaseRequest.java:[6,30] package io.swagger.annotations does not exist
也就是使用到的地方都报这个错误，由于common这个基本模块是第一构建的，common模块是构建成功。

通过Jenkins上运行mvn dependency:tree
树上starter-swagger子级空荡荡的。而类似于其他redis starter或者jpastarter子级树是有的。

目前的问题就是，Jenkins无法构建通过，麻烦大佬们有空帮忙看看

**Comment by dyc87112** [comment]
jenkins的maven仓库里删了重新下载下，可能之前下的不完整
