### ISSUE TITLE
swagger @RequestBody Map<String, Object> map 描述问题，老哥们。

### ISSUE THREAD

**Issue by longstorying** [SpringForAll/spring-boot-starter-swagger#88]
@ApiOperation(value = "测试")
    @PostMapping("index")
    @ApiImplicitParam(name = "map", value = "map集合")
    public String index(@RequestBody Map<String, Object> map) {
        return "111";
    }
比如前端传过来的是json ：{"name":"heihei","age":21}
像这种用map接收不用对象接收该怎么描述这个map。
这个map就是映射这个json的。swagger怎么描述呢。
知道的老哥希望能告诉我，谢谢！

**Comment by dyc87112** [comment]
Swagger自身不支持这种，自定义对象来描述
