### ISSUE TITLE
和zuul这种网关怎么整合呢？

### ISSUE THREAD

**Issue by windy05** [SpringForAll/spring-boot-starter-swagger#93]
如题

**Comment by Ruffianjiang** [comment]
@windy05 
有一个swagger聚合的项目，依赖zuul，把所有服务的swagger聚合在一起
https://gitee.com/didispace/swagger-butler

**Comment by windy05** [comment]
哇，非常感谢呢。。。我赶紧去star去

**Comment by Jiiiiiin** [comment]
当前插件也可以和网关整合，就不太清楚 其和 `swagger-butler`的区别在哪
